### ISSUE TITLE
Document which stage(s) uses each argument

### ISSUE THREAD

**Issue by kathy-snider** [DCAN-Labs/infant-abcd-bids-pipeline#16]
User can pass in all arguments no matter what stages are asked to run. It may not be obvious that not all stages use all of the arguments, so they might expect different output even though the stage(s) that use the argument he passed in doesn't use it. Add a table that shows what args are passed to what stages.

**Comment by audreymhoughton** [comment]
Marking this as resolved, as the documentation has been improved since this comment
