### ISSUE TITLE
Passing ASEG file as input

### ISSUE THREAD

**Issue by PNDhruman** [DCAN-Labs/infant-abcd-bids-pipeline#30]
Hello Developers,
In the latest version of the container there is an option to pass user generated aseg file to the pipeline. I was trying that option and it did not work correctly. On probing the code it seem that the aseg file is only copied as aseg_acpc.nii.gz without any transformation applied. The supplied aseg file is in the same space as the raw T1 and T2 images passed to the container. Since the T1 and T2 undergo may transformations, the aseg files should also go through the same transformations to be consistent with the processed T1 and T2 before being passed to the next stage. Your inputs to address this will be greatly appreciated. 
Thank you,
Dhruman

**Comment by LuciMoore** [comment]
Hello,

Apologies for the very delayed reply. Your point is an excellent one, however we are not actively developing this pipeline as we are now collaborating on the [Nibabies](https://github.com/nipreps/nibabies) pipeline instead for infant processing, so if this is still a relevant item, I would highly recommend that you try it out!
