### ISSUE TITLE
description bandstop filter flag usage

### ISSUE THREAD

**Issue by moser297** [DCAN-Labs/infant-abcd-bids-pipeline#33]
The description of this flag does not clearly indicate that the input should be in bpm and not in Hz (as Hz would be the usual choice for a band-stop filter, this should be clarified)
--bandstop LOWER UPPER
                        parameters for motion regressor band-stop filter. It
                        is recommended for the boundaries to match the inter-
                        quartile range for participant group respiratory rate
                        (bpm), or to match bids physio data directly [3].
                        These parameters are highly recommended for data
                        acquired with a frequency of approx. 1 Hz or more
                        (TR<=1.0). Default: no filter

**Comment by LuciMoore** [comment]
Thank you, @moser297! We have modified the README for clarity
